#*** Settings ***
#Library  AppiumLibrary
#Resource  ../TestCasesResources/SmokeTestCaseResources.robot
#Resource  ../CommonXpathsOrIDs/SmokeTestCaseXpathsOrIDs.robot



#*** Test Cases ***
#Test Case send email
#    send email



*** Settings ***
Documentation       Sending plain text email via Gmail.

Library             RPA.Email.ImapSmtp    smtp_server=smtp.gmail.com    smtp_port=587


*** Variables ***
${USERNAME}     malik.aakash@ilsainteractive.com
${PASSWORD}     malik0313
${RECIPIENT}    sheraz.hassan@ilsainteractive.com


*** Tasks ***
#*** Test Cases ***
Send test email
    Authorize    account=${USERNAME}    password=${PASSWORD}
    Send Message    sender=${USERNAME}
    ...    recipients=${RECIPIENT}
    ...    subject=Message generated by robot
    ...    body=This is the body of the email.
